import Head from 'next/head'
import Services from '../components/Services'
import Portfolio from '../components/Portfolio'
import Certificates from '../components/Certificates'
import { motion } from "framer-motion"
import { BsSun } from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillYoutube,
  AiOutlineLink,
  AiOutlineMail
} from 'react-icons/ai'
import Image from 'next/image'
import design from '../public/design.png'
import code from '../public/code.png'
import web0 from '../public/web0.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import web7 from '../public/web7.png'
import web8 from '../public/web8.png'
import web9 from '../public/web9.png'
import web10 from '../public/web10.png'


import Link from 'next/link'

import gfrontend from '../public/gfrontend.png'
import gcss from '../public/gcss.png'
import gjs from '../public/gjs.png'
import greact from '../public/greact.png'

import kevin from '../public/KevinPowell.png'
import bob from '../public/BobZiroll.png'
import { useState } from 'react'

export default function Home(props) {
  const [darkMode, setDarkMode] = useState(true);
  const inView1 = [-200, 0];
  const inView2 = [200, 0];


  // motion
  return (
    <div className={darkMode ? "dark" : ""}>
      {/* HEADER */}
      <Head>
        <title>Oleh's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* MAIN */}
      <main className='bg-white px-10 pb-10 max-sm:px-5 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-full pb-6'>

          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-teal-500'>osmdevelop</h1>
            <ul className='flex items-center w-56 justify-around'>
              <li>
                <BsSun onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
              </li>
              <li>
                <a href="#contact" className="flex hover:text-teal-300 dark:text-white 0 text-2xl transition duration-0 hover:duration-150">
                  <AiOutlineMail />
                </a>
              </li>
              <li>
                <a href="/OlehSmolikevychResume.pdf" className='bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md hover:from-cyan-500 transition duration-0 hover:duration-150'
                >Resume</a>
              </li>
            </ul>
          </nav>
          {/* TOP */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1, y: -35 }}
            transition={{
              duration: 0.8,
            }}
          >
            <div className='text-center md:py-20 p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl max-sm:text-4xl'>Oleh Smolikevych</h2>
              <h3 className='text-2xl py-2 md:text-3xl md:mt-10 dark:text-gray-100'>Front End Developer</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-400'>Front End Developer with passion building web pages and apps with React.js.</p>
            </div>
            {/* LINKS */}
            <div className='text-6xl flex justify-center gap-16 py-3 text-gray-600'>
              <a href="https://www.linkedin.com/in/olehsmolikevych/" target='_blank' className='
            hover:text-teal-300 
            transition duration-0 hover:duration-150'><AiFillLinkedin /></a>
              <a href="https://www.github.com/osmdevelop" target='_blank' className='
            hover:text-teal-300 
            transition duration-0 hover:duration-150'><AiFillGithub /></a>
            </div>
          </motion.div>
        </section>
        {/* SERVICES */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-teal-500'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>Since the beginning of my journey as a front end developer I've finished multiple
              <span className="text-teal-500"> courses </span>
              where I practiced building web pages and apps using modern technologies. I have done <span className="text-teal-500">freelance work</span> for people and small businesses.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I <span className="text-teal-500">rebuilt</span> websites and <span className="text-teal-500">keep up-to-date</span> information for newcomers from Ukraine in the United States to provide all necessary information which is crucial at the beginnings of the stay and adapt to the new environment.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <Services
              inView={inView1} /* The tough one */
              img={code}
              title="Front End Development"
              description="Building user-friendly web pages using modern tools"
              tool1="HTML"
              tool2="CSS / TailwindCSS, Bootstrap frameworks"
              tool3="JS / React.js, Next.js, other libraries and frameworks"
            />
            <Services
              inView={inView2}
              img={design}
              title="Creating Web pages using builders & IT Support"
              description="Creating and updating SEO focused web pages with builders. Site hosting. Business email management and providing tech support for proper and effective workflow"
              tool1="WIX"
              tool2="GoDaddy, Netlify"
              tool3="Office 365"
            />
          </div>
        </section>
        {/* PORTFOLIO */}
        <section>
          <div>
            <motion.div
              initial="offscreen"
              whileInView={{ x: [-200, 100], y: 26, scale: 1 }}
              transition={{
                duration: 0.8,
              }}
            >
              <h3 className='text-3xl py-1 text-teal-600'>Portfolio</h3></motion.div>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Some random text
              </p> */}
          </div>
          {/* PORTFOLIO IMAGES */}
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{
              duration: 0.8,
            }}
          >
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap items-center justify-between lg:justify-center'>

              <Portfolio
                web={web0}
                github="https://github.com/osmdevelop/bank-app"
                link="https://bank-app-novyi.netlify.app/"
              />
              <Portfolio
                web={web1}
                github="https://github.com/osmdevelop/space-travel"
                link="https://osmdevelop.github.io/space-travel/"
              />
              <Portfolio
                web={web2}
                github="https://github.com/osmdevelop/react-tenzies-game"
                link="https://osmdevelop.github.io/react-tenzies-game/"
              />
              <Portfolio
                web={web3}
                github="https://github.com/osmdevelop/react-movie-search"
                link="https://osmdevelop.github.io/react-movie-search/"
              />
              <Portfolio
                web={web4}
                github="https://github.com/osmdevelop/capital-hungry"
                link="https://osmdevelop.github.io/capital-hungry/"
              />
              <Portfolio
                web={web5}
                github="https://github.com/osmdevelop/react-speed-typing-game"
                link="https://osmdevelop.github.io/react-speed-typing-game/"
              />
              <Portfolio
                web={web10}
                github="https://github.com/osmdevelop/react-travel-journal"
                link="https://osmdevelop.github.io/react-travel-journal/"
              />
              <Portfolio
                web={web8}
                github="https://github.com/osmdevelop/momentum-clone"
                link="https://osmdevelop.github.io/momentum-clone/"
              />
              <Portfolio
                web={web9}
                github="https://github.com/osmdevelop/google-keep"
                link="https://osmdevelop.github.io/google-keep/"
              />

            </div>
          </motion.div>
        </section>
        {/* Certificates */}
        <section>
          <div>
            <h3 className='text-3xl py-1 text-teal-600'>Certificates</h3>
          </div>
          <div className='flex gap-6 max-lg:flex-col m-3'>
            <Certificates
              certificateLink="https://scrimba.com/certificate/uqQa4Rcq/gfrontend"
              certificateImg={gfrontend}
              certificateTitle="Front End Developer Career Path"
            />
            <Certificates
              certificateLink="https://scrimba.com/certificate/uqQa4Rcq/gresponsive"
              certificateImg={gcss}
              certificateTitle="Responsive Web Design"
            />
            <Certificates
              certificateLink="https://scrimba.com/certificate/uqQa4Rcq/gjavascript"
              certificateImg={gjs}
              certificateTitle="JavaScript Deep Dive"
            />
            <Certificates
              certificateLink="https://scrimba.com/certificate/uqQa4Rcq/greact"
              certificateImg={greact}
              certificateTitle="Advanced React"
            />
          </div>
        </section>
        {/* / Certificates */}
        {/* TUTORS */}
        <section>
          <div>
            <h3 className='text-3xl py-1 mt-9 text-teal-600'>Tutors</h3>
          </div>

          <div className='flex flex-col max-md: justify-around max-sm:gap-10 gap-10 py-6 lg:flex-row lg:flex-wrap items-center'>
            <div className='max-w-xs max-sm:w-4/5 rounded-lg p-6 shadow-lg dark:bg-sky-900 dark:text-gray-200'>
              <Image src={kevin}
                className='rounded-lg'
                width={300}
                height={300} />
              <h4 className='text-2xl mt-3 max-sm:text-xl'>Kevin Powell | <span className='text-teal-400'>CSS</span></h4>
              <p>CSS Evangelist. Teacher, Youtube content creator with over 600k subscribers</p>
              <div className='flex gap-3 text-3xl max-sm:justify-evenly mt-3'>
                <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://www.youtube.com/@KevinPowell"><AiFillYoutube /></a>
                <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://twitter.com/KevinJPowell"><AiFillTwitterCircle /></a>
                <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://www.kevinpowell.co/"><AiOutlineLink /></a>
              </div>
            </div>

            <div className='max-w-xs max-sm:w-4/5 rounded-lg p-6 shadow-lg dark:bg-sky-900 dark:text-gray-200'>
              <Image src={bob}
                className='rounded-lg'
                width={400}
                height={400} />
              <h4 className='text-2xl mt-3 max-sm:text-xl'>Bob Ziroll | <span className='text-teal-400'>React</span></h4>
              <p>Head of Education at Scrimba, contributor Freecodecamp</p>
              <div className='flex gap-3 text-3xl mt-3 max-sm:justify-evenly'>
                <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://www.linkedin.com/in/bobziroll/"><AiFillLinkedin /></a>
                <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://twitter.com/bobziroll"><AiFillTwitterCircle /></a>
                <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://scrimba.com/teachers/bobziroll"><AiOutlineLink /></a>
              </div>
            </div>
          </div>
        </section>
        {/* Contact */}
      </main>
      <footer className='bg-white px-10 pb-16 pt-6 max-sm:px-5 md:px-20 lg:px-40 dark:bg-sky-900 max-sm:pb-10'>
        <div>
          <h3 className='text-3xl py-1 text-teal-400'>Contact me</h3>
          <div className='dark:bg-sky-900 flex justify-center gap-3 items-center text-4xl text-teal-300 mt-6 max-sm:mt-5'>
            <AiOutlineMail className='dark:bg-sky-800 p-1 rounded-md text-6xl max-md:text-4xl max-ms:text-xl' />
            <a id='contact' className='hover:text-teal-500 duration-200 max-md:text-3xl max-sm:text-xl' href="mailto: oleh@osmdevelop.com" target="_blank" rel="noopener noreferrer">
              oleh@osmdevelop.com
            </a>
          </div>
        </div>
      </footer>
    </div >
  )
}