import Head from 'next/head'
import { BsSun } from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillYoutube,
  AiOutlineLink
} from 'react-icons/ai'
import Image from 'next/image'
import design from '../public/design.png'
import code from '../public/code.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'

import gfrontend from '../public/gfrontend.png'
import gcss from '../public/gcss.png'
import gjs from '../public/gjs.png'

import kevin from '../public/KevinPowell.png'
import bob from '../public/BobZiroll.png'
import { useState } from 'react'
// React reveal
// import Fade from 'react-reveal/Fade';
// import Zoom from 'react-reveal/Zoom';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      {/* HEADER */}
      <Head>
        <title>Oleh's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* MAIN */}
      <main className='bg-white px-10 pb-10 max-sm:px-5 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-full pb-6'>

          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-teal-500'>osmdevelop</h1>
            <ul className='flex items-center'>
              <li>
                <BsSun onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8 hover:from-cyan-500 to-teal-500 bg-cyan-500 transition duration-0 hover:duration-150' href="#">Resume</a>
              </li>
            </ul>
          </nav>
          {/* TOP */}
            <div className='text-center md:py-20 p-10'>
          {/* <Fade top> */}
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl max-sm:text-4xl'>Oleh Smolikevych</h2>
          {/* </Fade> */}
              <h3 className='text-2xl py-2 md:text-3xl md:mt-10 dark:text-gray-100'>Front End Developer</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-400'>Front End Developer with passion building web pages and apps with React.js.</p>
            </div>
          {/* LINKS */}
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://www.linkedin.com/in/olehsmolikevych/" className='
            hover:text-teal-300 
            transition duration-0 hover:duration-150'><AiFillLinkedin /></a>
            <a href="https://www.github.com/osmdevelop" className='
            hover:text-teal-300 
            transition duration-0 hover:duration-150'><AiFillGithub /></a>
            <a href="https://www.twitter.com/OlehSml" className='
            hover:text-teal-300 
            transition duration-0 hover:duration-150'><AiFillTwitterCircle /></a>
          </div>
        </section>
        {/* SERVICES */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-teal-500'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>Since the beginning of my journey as a front end developer I've finished multiple
              <span className="text-teal-500"> courses </span>
              where I practiced building web pages and apps using modern technologies. I have done <span className="text-teal-500">freelance work</span> for people and small businesses.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Currently I <span className="text-teal-500">build</span> and <span className="text-teal-500">update</span> web pages for newcomers from Ukraine to the United States to provide all necessary information which is crucial at the beginnings of the stay and adapt to the new environment.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            {/* <Fade left> */}
              <div className="text-center shadow-lg p-10 rounded-xl my-10  flex-1 dark:bg-sky-900 dark:text-gray-200 flex flex-col justify-center items-center">
                <Image src={code} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2'>Front End Development</h3>
                <p className='py-2'>Building user-friendly web pages using modern tools</p>
                <h4 className='py-4 text-teal-400'>Tools I use</h4>
                <p className='text-gray-800 py-1 dark:text-sky-200'>HTML</p>
                <p className='text-gray-800 py-1 dark:text-sky-200'>CSS / Tailwind, Bootstrap frameworks</p>
                <p className='text-gray-800 py-1 dark:text-sky-200'>JS / React.js & package managers</p>
              </div>
            {/* </Fade> */}
            {/* <Fade right> */}
              <div className="text-center shadow-lg p-10 rounded-xl my-10  flex-1 dark:bg-sky-900 dark:text-gray-200 flex flex-col">
                <Image src={design} width={100} height={100} className="self-center" />
                <h3 className='text-lg font-medium pt-8 pb-2'>Creating Web pages using builders & IT Support</h3>
                <p className='py-2'>Creating and updating SEO focused web pages with builders. Site hosting. Business email management and providing tech support for proper and effective workflow</p>
                <h4 className='py-4 text-teal-400'>Tools I use</h4>
                <p className='text-gray-800 py-1 dark:text-sky-200'>WIX</p>
                <p className='text-gray-800 py-1 dark:text-sky-200'>GoDaddy</p>
                <p className='text-gray-800 py-1 dark:text-sky-200'>Office 365</p>
              </div>
            {/* </Fade> */}
          </div>
        </section>
        {/* PORTFOLIO */}
        <section>
          <div>
            <h3 className='text-3xl py-1 text-teal-600'>Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Some random text
              {/* <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use. */}
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          {/* PORTFOLIO IMAGES */}
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap items-center '>
            {/* <Zoom> */}
              <div className='basis-1/3 flex-1'>
                <Image src={web1}
                  className='rounded-lg object-cover'
                  width={"100%"}
                  height={"100%"} />
                <a className='right-0 text-6xl bg-slate-700 rounded-full
                text-white absolute mr-3 p-1 -mt-20 round w-100 
                hover:text-teal-300 
                  transition duration-0 hover:duration-150
                  max-sm:text-5xl max-sm:-mt-16 max-sm:mr-1.5' target='_blank' href="https://github.com/osmdevelop/react-tenzies-game"><AiFillGithub className='-mt-px self-end' />
                </a>
              </div>
            {/* </Zoom> */}
            {/* <Zoom> */}
              <div className='basis-1/3 flex-1'>
                <Image src={web2}
                  className='rounded-lg object-cover'
                  width={"100%"}
                  height={"100%"}
                />
                <a className='right-0 text-6xl bg-slate-700 rounded-full
                text-white absolute mr-3 p-1 -mt-20 round w-100 
                hover:text-teal-300 
                  transition duration-0 hover:duration-150
                  max-sm:text-5xl max-sm:-mt-16 max-sm:mr-1.5' target='_blank' href="https://github.com/osmdevelop/react-tenzies-game"><AiFillGithub className='-mt-px self-end' />
                </a>
              </div>
            {/* </Zoom> */}
            {/* <Zoom> */}
              <div className='basis-1/3 flex-1'>
                <Image src={web3}
                  className='rounded-lg object-cover'
                  width={"100%"}
                  height={"100%"} />
                <a className='right-0 text-6xl bg-slate-700 rounded-full
                text-white absolute mr-3 p-1 -mt-20 round w-100 
                hover:text-teal-300 
                  transition duration-0 hover:duration-150
                  max-sm:text-5xl max-sm:-mt-16 max-sm:mr-1.5' target='_blank' href="https://github.com/osmdevelop/react-tenzies-game"><AiFillGithub className='-mt-px self-end' />
                </a>
              </div>
            {/* </Zoom>
            <Zoom> */}
              <div className='basis-1/3 flex-1'>
                <Image src={web4}
                  className='rounded-lg object-cover'
                  width={"100%"}
                  height={"100%"} />
                  <a className='right-0 text-6xl bg-slate-700 rounded-full
                text-white absolute mr-3 p-1 -mt-20 round w-100 
                hover:text-teal-300 
                  transition duration-0 hover:duration-150
                  max-sm:text-5xl max-sm:-mt-16 max-sm:mr-1.5' target='_blank' href="https://github.com/osmdevelop/react-tenzies-game"><AiFillGithub className='-mt-px self-end' />
                </a>
              </div>
            {/* </Zoom>
            <Zoom> */}
              <div className='basis-1/3 flex-1'>
                <Image src={web5}
                  className='rounded-lg object-cover'
                  width={"100%"}
                  height={"100%"} />
                <a className='right-0 text-6xl bg-slate-700 rounded-full
                text-white absolute mr-3 p-1 -mt-20 round w-100 
                  hover:text-teal-300 
                    transition duration-0 hover:duration-150
                    max-sm:text-5xl max-sm:-mt-16 max-sm:mr-1.5' target='_blank' href="https://github.com/osmdevelop/react-tenzies-game"><AiFillGithub className='-mt-px self-end' />
                  </a>
              </div>
            {/* </Zoom>
            <Zoom> */}
              <div className='basis-1/3 flex-1 border'>
                <Image
                  src={web6}
                  className='rounded-lg object-cover'
                  width={"100%"}
                  height={"100%"} 
                  />
                  <a className='right-0 text-6xl bg-slate-700 rounded-full
                text-white absolute mr-3 p-1 -mt-20 round w-100 
                hover:text-teal-300 
                transition duration-0 hover:duration-150
                max-sm:text-5xl max-sm:-mt-16 max-sm:mr-1.5' target='_blank' href="https://github.com/osmdevelop/react-tenzies-game"><AiFillGithub className='-mt-px self-end' />
                  </a>
                </div>
            {/* </Zoom> */}
          </div>
        </section>
        {/* Certificates */}
        <section>
            <div>
              <h3 className='text-3xl py-1 text-teal-600'>Certificates</h3>
            </div>
            <div className='flex gap-3 max-lg:flex-col'>
              <div>
                <Image src={gfrontend}
                    className='rounded-lg object-cover'
                    width={"100%"}
                    height={"100%"} />
              </div>
              <div>
                <Image src={gcss}
                    className='rounded-lg object-cover'
                    width={"100%"}
                    height={"100%"} />
              </div>
              <div>
                <Image src={gjs}
                    className='rounded-lg object-cover'
                    width={"100%"}
                    height={"100%"} />
              </div>
            </div>
        </section>
        {/* / Certificates */}
        {/* TUTORS */}
        <section>
            <div>
              <h3 className='text-3xl py-1 text-teal-600'>Tutors</h3>
            </div>

            <div className='flex flex-col max-md: justify-around max-sm:gap-10   gap-10 py-10 lg:flex-row lg:flex-wrap items-center'>
              <div className='max-w-xs max-sm:w-4/5 rounded-lg p-6 shadow-lg dark:bg-sky-900 dark:text-gray-200'>
                <Image src={kevin} 
                className='rounded-lg'
                width={300}
                height={300} />
                <h4 className='text-2xl mt-3 max-sm:text-xl'>Kevin Powell | <span className='text-teal-400'>CSS</span></h4>
                <p>CSS Evangelist. Teacher, Youtube content creator with over 600k subscribers</p>
                <div className='flex gap-3 text-3xl max-sm:justify-evenly mt-3'>
                  <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://www.youtube.com/@KevinPowell"><AiFillYoutube /></a>
                  <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://twitter.com/KevinJPowell"><AiFillTwitterCircle /></a>
                  <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://www.kevinpowell.co/"><AiOutlineLink /></a>
                </div>
              </div>
              
              <div className='max-w-xs max-sm:w-4/5 rounded-lg p-6 shadow-lg dark:bg-sky-900 dark:text-gray-200'>
                <Image src={bob} 
                className='rounded-lg'
                width={400}
                height={400} />
                <h4 className='text-2xl mt-3 max-sm:text-xl'>Bob Ziroll | <span className='text-teal-400'>React</span></h4>
                <p>Head of Education at Scrimba, contributor Freecodecamp</p>
                <div className='flex gap-3 text-3xl mt-3 max-sm:justify-evenly'>
                  <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://www.linkedin.com/in/bobziroll/"><AiFillLinkedin /></a>
                  <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://twitter.com/bobziroll"><AiFillTwitterCircle /></a>
                  <a className='hover:text-teal-300 
                  transition duration-0 hover:duration-150' target='_blank' href="https://scrimba.com/teachers/bobziroll"><AiOutlineLink /></a>
                </div>
              </div>
            </div>
        </section>
      </main>
    </div>
  )
}
